// Code generated by goctl. DO NOT EDIT.
package types

type GenerateQrcodeReq struct {
}

type GenerateQrcodeResp struct {
	Qrcode string `json:"qrCode"`
	T      int64  `json:"t"`
	Ck     string `json:"ck"`
}

type QrcodeStateReq struct {
	T  int64  `json:"t"`
	Ck string `json:"ck"`
}

type QrcodeStateResp struct {
	UserName     string `json:"userName"`
	UserID       string `json:"userId"`
	TokenType    string `json:"tokenType"`
	RefreshToken string `json:"refreshToken"`
}

type GetAccessTokenFromRefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type GetAccessTokenFromRefreshTokenResp struct {
	AccessTokenType string `json:"accessTokenType"`
	AccessToken     string `json:"accessToken"`
	RefreshToken    string `json:"refreshToken"`
	ExpiresIn       int    `json:"expiresIn"`
	ExpireTime      string `json:"expireTime"`
}
